
package com.pluralsight.catalog.rpc;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "DepartmentSupplierService", targetNamespace = "http://rpc.catalog.pluralsight.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DepartmentSupplierService {


    /**
     * 
     * @param department
     * @return
     *     returns int
     */
    @WebMethod(action = "http://rpc.catalog.pluralsight.com/DepartmentSupplierService/getSupplierPerDepartment")
    @WebResult(name = "supplier", partName = "supplier")
    public int getSupplierPerDepartment(
        @WebParam(name = "department", partName = "department")
        String department);

}
