
package com.pluralsight.catalog.rpc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "DepartmentSupplierService", targetNamespace = "http://rpc.catalog.pluralsight.com/", wsdlLocation = "file:/workspaces/GlobomanticsCompanyCatalog/Module_3/src/main/resources/DepartmentSupplierService.wsdl")
public class DepartmentSupplierService_Service
    extends Service
{

    private static final URL DEPARTMENTSUPPLIERSERVICE_WSDL_LOCATION;
    private static final WebServiceException DEPARTMENTSUPPLIERSERVICE_EXCEPTION;
    private static final QName DEPARTMENTSUPPLIERSERVICE_QNAME = new QName("http://rpc.catalog.pluralsight.com/", "DepartmentSupplierService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/workspaces/GlobomanticsCompanyCatalog/Module_3/src/main/resources/DepartmentSupplierService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEPARTMENTSUPPLIERSERVICE_WSDL_LOCATION = url;
        DEPARTMENTSUPPLIERSERVICE_EXCEPTION = e;
    }

    public DepartmentSupplierService_Service() {
        super(__getWsdlLocation(), DEPARTMENTSUPPLIERSERVICE_QNAME);
    }

    public DepartmentSupplierService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEPARTMENTSUPPLIERSERVICE_QNAME, features);
    }

    public DepartmentSupplierService_Service(URL wsdlLocation) {
        super(wsdlLocation, DEPARTMENTSUPPLIERSERVICE_QNAME);
    }

    public DepartmentSupplierService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEPARTMENTSUPPLIERSERVICE_QNAME, features);
    }

    public DepartmentSupplierService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DepartmentSupplierService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DepartmentSupplierService
     */
    @WebEndpoint(name = "DepartmentSupplierServiceSOAP")
    public DepartmentSupplierService getDepartmentSupplierServiceSOAP() {
        return super.getPort(new QName("http://rpc.catalog.pluralsight.com/", "DepartmentSupplierServiceSOAP"), DepartmentSupplierService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DepartmentSupplierService
     */
    @WebEndpoint(name = "DepartmentSupplierServiceSOAP")
    public DepartmentSupplierService getDepartmentSupplierServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://rpc.catalog.pluralsight.com/", "DepartmentSupplierServiceSOAP"), DepartmentSupplierService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEPARTMENTSUPPLIERSERVICE_EXCEPTION!= null) {
            throw DEPARTMENTSUPPLIERSERVICE_EXCEPTION;
        }
        return DEPARTMENTSUPPLIERSERVICE_WSDL_LOCATION;
    }

}
